export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';

export const GET_MOVIES_LIKE = 'GET_MOVIES_LIKE';
export const SET_MOVIES_LIKE = 'SET_MOVIES_LIKE';

export const ADD_REACTION = 'ADD_REACTION';

export const INCREMENT_VIEWS = 'INCREMENT_VIEWS';

export const GET_GENRES = 'GET_GENRES';
export const SET_GENRES = 'SET_GENRES';

export const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';

export const ADD_COMMENT = 'ADD_COMMENT';

export const GET_COMMENTS_FOR_MOVIE = 'GET_COMMENTS_FOR_MOVIE';
export const SET_COMMENTS_FOR_MOVIE = 'SET_COMMENTS_FOR_MOVIE';

export const GET_HOTEST_MOVIES = 'GET_HOTEST_MOVIES';
export const SET_HOTEST_MOVIES = 'SET_HOTEST_MOVIES';

export const GET_RELATED_MOVIES = 'GET_RELATED_MOVIES';
export const SET_RELATED_MOVIES = 'SET_RELATED_MOVIES';
